sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /camera/depth_registered/points
   max_range: 5.0
   frame_subsample: 1
   point_subsample: 1
   shape_offset: 0
   shape_scale: 1.0
   shape_padding: 0.05
